apiVersion: apps/v1
kind: Deployment
metadata:
  name: analytics-worker
  namespace: nba-event-platform
spec:
  replicas: 1
  selector:
    matchLabels:
      app: analytics-worker
  template:
    metadata:
      labels:
        app: analytics-worker
    spec:
      containers:
        - name: analytics-worker
          image: nba-event-platform-analytics-worker:latest
          imagePullPolicy: Never
          envFrom:
            - configMapRef:
                name: application-config
            - secretRef:
                name: application-credentials
          env:
            - name: CONSUMER_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
